/*
	Generated by KBEngine!
	Please do not modify this file!
	tools = kbcmd
*/

namespace KBEngine
{
	using UnityEngine;
	using System;
	using System.Collections;
	using System.Collections.Generic;

	public class EntityDef
	{
		public static Dictionary<string, UInt16> datatype2id = new Dictionary<string, UInt16>();
		public static Dictionary<string, DATATYPE_BASE> datatypes = new Dictionary<string, DATATYPE_BASE>();
		public static Dictionary<UInt16, DATATYPE_BASE> id2datatypes = new Dictionary<UInt16, DATATYPE_BASE>();
		public static Dictionary<string, Int32> entityclass = new Dictionary<string, Int32>();
		public static Dictionary<string, ScriptModule> moduledefs = new Dictionary<string, ScriptModule>();
		public static Dictionary<UInt16, ScriptModule> idmoduledefs = new Dictionary<UInt16, ScriptModule>();

		public static bool init()
		{
			initDataTypes();
			initDefTypes();
			initScriptModules();
			return true;
		}

		public static bool reset()
		{
			clear();
			return init();
		}

		public static void clear()
		{
			datatype2id.Clear();
			datatypes.Clear();
			id2datatypes.Clear();
			entityclass.Clear();
			moduledefs.Clear();
			idmoduledefs.Clear();
		}

		public static void initDataTypes()
		{
			datatypes["UINT8"] = new DATATYPE_UINT8();
			datatypes["UINT16"] = new DATATYPE_UINT16();
			datatypes["UINT32"] = new DATATYPE_UINT32();
			datatypes["UINT64"] = new DATATYPE_UINT64();

			datatypes["INT8"] = new DATATYPE_INT8();
			datatypes["INT16"] = new DATATYPE_INT16();
			datatypes["INT32"] = new DATATYPE_INT32();
			datatypes["INT64"] = new DATATYPE_INT64();

			datatypes["FLOAT"] = new DATATYPE_FLOAT();
			datatypes["DOUBLE"] = new DATATYPE_DOUBLE();

			datatypes["STRING"] = new DATATYPE_STRING();
			datatypes["VECTOR2"] = new DATATYPE_VECTOR2();

			datatypes["VECTOR3"] = new DATATYPE_VECTOR3();

			datatypes["VECTOR4"] = new DATATYPE_VECTOR4();
			datatypes["PYTHON"] = new DATATYPE_PYTHON();

			datatypes["UNICODE"] = new DATATYPE_UNICODE();
			datatypes["ENTITYCALL"] = new DATATYPE_ENTITYCALL();

			datatypes["BLOB"] = new DATATYPE_BLOB();
		}

		public static void initScriptModules()
		{
			ScriptModule pAccountModule = new ScriptModule("Account");
			EntityDef.moduledefs["Account"] = pAccountModule;
			EntityDef.idmoduledefs[1] = pAccountModule;

			Property pAccount_position = new Property();
			pAccount_position.name = "position";
			pAccount_position.properUtype = 40000;
			pAccount_position.properFlags = 4;
			pAccount_position.aliasID = 1;
			Vector3 Account_position_defval = new Vector3();
			pAccount_position.defaultVal = Account_position_defval;
			pAccountModule.propertys["position"] = pAccount_position; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_position.aliasID] = pAccount_position;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(position / 40000).");

			Property pAccount_direction = new Property();
			pAccount_direction.name = "direction";
			pAccount_direction.properUtype = 40001;
			pAccount_direction.properFlags = 4;
			pAccount_direction.aliasID = 2;
			Vector3 Account_direction_defval = new Vector3();
			pAccount_direction.defaultVal = Account_direction_defval;
			pAccountModule.propertys["direction"] = pAccount_direction; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_direction.aliasID] = pAccount_direction;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(direction / 40001).");

			Property pAccount_spaceID = new Property();
			pAccount_spaceID.name = "spaceID";
			pAccount_spaceID.properUtype = 40002;
			pAccount_spaceID.properFlags = 16;
			pAccount_spaceID.aliasID = 3;
			UInt32 Account_spaceID_defval;
			UInt32.TryParse("", out Account_spaceID_defval);
			pAccount_spaceID.defaultVal = Account_spaceID_defval;
			pAccountModule.propertys["spaceID"] = pAccount_spaceID; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_spaceID.aliasID] = pAccount_spaceID;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(spaceID / 40002).");

			Property pAccount_isNewPlayer = new Property();
			pAccount_isNewPlayer.name = "isNewPlayer";
			pAccount_isNewPlayer.properUtype = 5;
			pAccount_isNewPlayer.properFlags = 32;
			pAccount_isNewPlayer.aliasID = 4;
			Byte Account_isNewPlayer_defval;
			Byte.TryParse("1", out Account_isNewPlayer_defval);
			pAccount_isNewPlayer.defaultVal = Account_isNewPlayer_defval;
			pAccountModule.propertys["isNewPlayer"] = pAccount_isNewPlayer; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_isNewPlayer.aliasID] = pAccount_isNewPlayer;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(isNewPlayer / 5).");

			Property pAccount_playerID = new Property();
			pAccount_playerID.name = "playerID";
			pAccount_playerID.properUtype = 4;
			pAccount_playerID.properFlags = 4;
			pAccount_playerID.aliasID = 5;
			UInt16 Account_playerID_defval;
			UInt16.TryParse("", out Account_playerID_defval);
			pAccount_playerID.defaultVal = Account_playerID_defval;
			pAccountModule.propertys["playerID"] = pAccount_playerID; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_playerID.aliasID] = pAccount_playerID;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(playerID / 4).");

			Property pAccount_playerID_base = new Property();
			pAccount_playerID_base.name = "playerID_base";
			pAccount_playerID_base.properUtype = 2;
			pAccount_playerID_base.properFlags = 32;
			pAccount_playerID_base.aliasID = 6;
			UInt16 Account_playerID_base_defval;
			UInt16.TryParse("", out Account_playerID_base_defval);
			pAccount_playerID_base.defaultVal = Account_playerID_base_defval;
			pAccountModule.propertys["playerID_base"] = pAccount_playerID_base; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_playerID_base.aliasID] = pAccount_playerID_base;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(playerID_base / 2).");

			Property pAccount_playerName = new Property();
			pAccount_playerName.name = "playerName";
			pAccount_playerName.properUtype = 3;
			pAccount_playerName.properFlags = 4;
			pAccount_playerName.aliasID = 7;
			string Account_playerName_defval = "";
			pAccount_playerName.defaultVal = Account_playerName_defval;
			pAccountModule.propertys["playerName"] = pAccount_playerName; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_playerName.aliasID] = pAccount_playerName;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(playerName / 3).");

			Property pAccount_playerName_base = new Property();
			pAccount_playerName_base.name = "playerName_base";
			pAccount_playerName_base.properUtype = 1;
			pAccount_playerName_base.properFlags = 32;
			pAccount_playerName_base.aliasID = 8;
			string Account_playerName_base_defval = "";
			pAccount_playerName_base.defaultVal = Account_playerName_base_defval;
			pAccountModule.propertys["playerName_base"] = pAccount_playerName_base; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_playerName_base.aliasID] = pAccount_playerName_base;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(playerName_base / 1).");

			List<DATATYPE_BASE> pAccount_OnReqCreateAvatar_args = new List<DATATYPE_BASE>();
			pAccount_OnReqCreateAvatar_args.Add(EntityDef.id2datatypes[2]);

			Method pAccount_OnReqCreateAvatar = new Method();
			pAccount_OnReqCreateAvatar.name = "OnReqCreateAvatar";
			pAccount_OnReqCreateAvatar.methodUtype = 6;
			pAccount_OnReqCreateAvatar.aliasID = 1;
			pAccount_OnReqCreateAvatar.args = pAccount_OnReqCreateAvatar_args;

			pAccountModule.methods["OnReqCreateAvatar"] = pAccount_OnReqCreateAvatar; 
			pAccountModule.useMethodDescrAlias = true;
			pAccountModule.idmethods[(UInt16)pAccount_OnReqCreateAvatar.aliasID] = pAccount_OnReqCreateAvatar;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(OnReqCreateAvatar / 6).");

			List<DATATYPE_BASE> pAccount_playerLevelRoom_args = new List<DATATYPE_BASE>();

			Method pAccount_playerLevelRoom = new Method();
			pAccount_playerLevelRoom.name = "playerLevelRoom";
			pAccount_playerLevelRoom.methodUtype = 7;
			pAccount_playerLevelRoom.aliasID = 2;
			pAccount_playerLevelRoom.args = pAccount_playerLevelRoom_args;

			pAccountModule.methods["playerLevelRoom"] = pAccount_playerLevelRoom; 
			pAccountModule.useMethodDescrAlias = true;
			pAccountModule.idmethods[(UInt16)pAccount_playerLevelRoom.aliasID] = pAccount_playerLevelRoom;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(playerLevelRoom / 7).");

			List<DATATYPE_BASE> pAccount_EnterMatchesMatch_args = new List<DATATYPE_BASE>();

			Method pAccount_EnterMatchesMatch = new Method();
			pAccount_EnterMatchesMatch.name = "EnterMatchesMatch";
			pAccount_EnterMatchesMatch.methodUtype = 4;
			pAccount_EnterMatchesMatch.aliasID = -1;
			pAccount_EnterMatchesMatch.args = pAccount_EnterMatchesMatch_args;

			pAccountModule.methods["EnterMatchesMatch"] = pAccount_EnterMatchesMatch; 
			pAccountModule.base_methods["EnterMatchesMatch"] = pAccount_EnterMatchesMatch;

			pAccountModule.idbase_methods[pAccount_EnterMatchesMatch.methodUtype] = pAccount_EnterMatchesMatch;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(EnterMatchesMatch / 4).");

			List<DATATYPE_BASE> pAccount_reqCreateAvatar_args = new List<DATATYPE_BASE>();
			pAccount_reqCreateAvatar_args.Add(EntityDef.id2datatypes[12]);

			Method pAccount_reqCreateAvatar = new Method();
			pAccount_reqCreateAvatar.name = "reqCreateAvatar";
			pAccount_reqCreateAvatar.methodUtype = 2;
			pAccount_reqCreateAvatar.aliasID = -1;
			pAccount_reqCreateAvatar.args = pAccount_reqCreateAvatar_args;

			pAccountModule.methods["reqCreateAvatar"] = pAccount_reqCreateAvatar; 
			pAccountModule.base_methods["reqCreateAvatar"] = pAccount_reqCreateAvatar;

			pAccountModule.idbase_methods[pAccount_reqCreateAvatar.methodUtype] = pAccount_reqCreateAvatar;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(reqCreateAvatar / 2).");

			List<DATATYPE_BASE> pAccount_LeaveRoom_args = new List<DATATYPE_BASE>();

			Method pAccount_LeaveRoom = new Method();
			pAccount_LeaveRoom.name = "LeaveRoom";
			pAccount_LeaveRoom.methodUtype = 1;
			pAccount_LeaveRoom.aliasID = -1;
			pAccount_LeaveRoom.args = pAccount_LeaveRoom_args;

			pAccountModule.methods["LeaveRoom"] = pAccount_LeaveRoom; 
			pAccountModule.cell_methods["LeaveRoom"] = pAccount_LeaveRoom;

			pAccountModule.idcell_methods[pAccount_LeaveRoom.methodUtype] = pAccount_LeaveRoom;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(LeaveRoom / 1).");

			ScriptModule pRoomModule = new ScriptModule("Room");
			EntityDef.moduledefs["Room"] = pRoomModule;
			EntityDef.idmoduledefs[4] = pRoomModule;

			Property pRoom_position = new Property();
			pRoom_position.name = "position";
			pRoom_position.properUtype = 40000;
			pRoom_position.properFlags = 4;
			pRoom_position.aliasID = 1;
			Vector3 Room_position_defval = new Vector3();
			pRoom_position.defaultVal = Room_position_defval;
			pRoomModule.propertys["position"] = pRoom_position; 

			pRoomModule.usePropertyDescrAlias = true;
			pRoomModule.idpropertys[(UInt16)pRoom_position.aliasID] = pRoom_position;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Room), property(position / 40000).");

			Property pRoom_direction = new Property();
			pRoom_direction.name = "direction";
			pRoom_direction.properUtype = 40001;
			pRoom_direction.properFlags = 4;
			pRoom_direction.aliasID = 2;
			Vector3 Room_direction_defval = new Vector3();
			pRoom_direction.defaultVal = Room_direction_defval;
			pRoomModule.propertys["direction"] = pRoom_direction; 

			pRoomModule.usePropertyDescrAlias = true;
			pRoomModule.idpropertys[(UInt16)pRoom_direction.aliasID] = pRoom_direction;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Room), property(direction / 40001).");

			Property pRoom_spaceID = new Property();
			pRoom_spaceID.name = "spaceID";
			pRoom_spaceID.properUtype = 40002;
			pRoom_spaceID.properFlags = 16;
			pRoom_spaceID.aliasID = 3;
			UInt32 Room_spaceID_defval;
			UInt32.TryParse("", out Room_spaceID_defval);
			pRoom_spaceID.defaultVal = Room_spaceID_defval;
			pRoomModule.propertys["spaceID"] = pRoom_spaceID; 

			pRoomModule.usePropertyDescrAlias = true;
			pRoomModule.idpropertys[(UInt16)pRoom_spaceID.aliasID] = pRoom_spaceID;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Room), property(spaceID / 40002).");

			Property pRoom_RoomType = new Property();
			pRoom_RoomType.name = "RoomType";
			pRoom_RoomType.properUtype = 8;
			pRoom_RoomType.properFlags = 4;
			pRoom_RoomType.aliasID = 4;
			Byte Room_RoomType_defval;
			Byte.TryParse("", out Room_RoomType_defval);
			pRoom_RoomType.defaultVal = Room_RoomType_defval;
			pRoomModule.propertys["RoomType"] = pRoom_RoomType; 

			pRoomModule.usePropertyDescrAlias = true;
			pRoomModule.idpropertys[(UInt16)pRoom_RoomType.aliasID] = pRoom_RoomType;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Room), property(RoomType / 8).");

			Property pRoom_playerMaxCount = new Property();
			pRoom_playerMaxCount.name = "playerMaxCount";
			pRoom_playerMaxCount.properUtype = 10;
			pRoom_playerMaxCount.properFlags = 4;
			pRoom_playerMaxCount.aliasID = 5;
			Byte Room_playerMaxCount_defval;
			Byte.TryParse("", out Room_playerMaxCount_defval);
			pRoom_playerMaxCount.defaultVal = Room_playerMaxCount_defval;
			pRoomModule.propertys["playerMaxCount"] = pRoom_playerMaxCount; 

			pRoomModule.usePropertyDescrAlias = true;
			pRoomModule.idpropertys[(UInt16)pRoom_playerMaxCount.aliasID] = pRoom_playerMaxCount;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Room), property(playerMaxCount / 10).");

			Property pRoom_roomKey = new Property();
			pRoom_roomKey.name = "roomKey";
			pRoom_roomKey.properUtype = 7;
			pRoom_roomKey.properFlags = 4;
			pRoom_roomKey.aliasID = 6;
			UInt64 Room_roomKey_defval;
			UInt64.TryParse("", out Room_roomKey_defval);
			pRoom_roomKey.defaultVal = Room_roomKey_defval;
			pRoomModule.propertys["roomKey"] = pRoom_roomKey; 

			pRoomModule.usePropertyDescrAlias = true;
			pRoomModule.idpropertys[(UInt16)pRoom_roomKey.aliasID] = pRoom_roomKey;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Room), property(roomKey / 7).");

		}

		public static void initDefTypes()
		{
			{
				UInt16 utype = 2;
				string typeName = "UINT8";
				string name = "UINT8";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 3;
				string typeName = "UINT16";
				string name = "UINT16";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 5;
				string typeName = "SPACE_KEY";
				string name = "UINT64";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 4;
				string typeName = "ENTITY_ID";
				string name = "UINT32";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 6;
				string typeName = "INT8";
				string name = "INT8";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 7;
				string typeName = "INT16";
				string name = "INT16";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 8;
				string typeName = "INT32";
				string name = "INT32";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 9;
				string typeName = "INT64";
				string name = "INT64";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 1;
				string typeName = "STRING";
				string name = "STRING";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 12;
				string typeName = "UNICODE";
				string name = "UNICODE";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 13;
				string typeName = "FLOAT";
				string name = "FLOAT";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 14;
				string typeName = "DOUBLE";
				string name = "DOUBLE";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 10;
				string typeName = "PYTHON";
				string name = "PYTHON";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 10;
				string typeName = "PY_DICT";
				string name = "PY_DICT";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 10;
				string typeName = "PY_TUPLE";
				string name = "PY_TUPLE";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 10;
				string typeName = "PY_LIST";
				string name = "PY_LIST";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 10;
				string typeName = "ENTITYCALL";
				string name = "ENTITYCALL";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 11;
				string typeName = "BLOB";
				string name = "BLOB";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 15;
				string typeName = "VECTOR2";
				string name = "VECTOR2";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 16;
				string typeName = "VECTOR3";
				string name = "VECTOR3";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 17;
				string typeName = "VECTOR4";
				string name = "VECTOR4";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 22;
				string typeName = "ENTITY_LIST";
				DATATYPE_ENTITY_LIST datatype = new DATATYPE_ENTITY_LIST();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			foreach(string datatypeStr in EntityDef.datatypes.Keys)
			{
				DATATYPE_BASE dataType = EntityDef.datatypes[datatypeStr];
				if(dataType != null)
				{
					dataType.bind();
				}
			}
		}

	}


}