/*
	Generated by KBEngine!
	Please do not modify this file!
	
	tools = kbcmd
*/

namespace KBEngine
{
	using UnityEngine;
	using System;
	using System.Collections;
	using System.Collections.Generic;

	// defined in */scripts/entity_defs/Account.def
	public class EntityBaseEntityCall_AccountBase : EntityCall
	{

		public EntityBaseEntityCall_AccountBase(Int32 eid, string ename) : base(eid, ename)
		{
			type = ENTITYCALL_TYPE.ENTITYCALL_TYPE_BASE;
		}

		public void EnterMatchesMatch()
		{
			Bundle pBundle = newCall("EnterMatchesMatch", 0);
			if(pBundle == null)
				return;

			sendCall(null);
		}

		public void reqAddFriend(UInt64 arg1)
		{
			Bundle pBundle = newCall("reqAddFriend", 0);
			if(pBundle == null)
				return;

			bundle.writeUint64(arg1);
			sendCall(null);
		}

		public void reqAgreeAddFriendByMail(Int32 arg1)
		{
			Bundle pBundle = newCall("reqAgreeAddFriendByMail", 0);
			if(pBundle == null)
				return;

			bundle.writeInt32(arg1);
			sendCall(null);
		}

		public void reqChangeRoom()
		{
			Bundle pBundle = newCall("reqChangeRoom", 0);
			if(pBundle == null)
				return;

			sendCall(null);
		}

		public void reqCreateAvatar(string arg1)
		{
			Bundle pBundle = newCall("reqCreateAvatar", 0);
			if(pBundle == null)
				return;

			bundle.writeUnicode(arg1);
			sendCall(null);
		}

		public void reqDeleMail(Int32 arg1)
		{
			Bundle pBundle = newCall("reqDeleMail", 0);
			if(pBundle == null)
				return;

			bundle.writeInt32(arg1);
			sendCall(null);
		}

		public void reqFriendsList()
		{
			Bundle pBundle = newCall("reqFriendsList", 0);
			if(pBundle == null)
				return;

			sendCall(null);
		}

		public void reqGetOtherGiveGold(Int32 arg1)
		{
			Bundle pBundle = newCall("reqGetOtherGiveGold", 0);
			if(pBundle == null)
				return;

			bundle.writeInt32(arg1);
			sendCall(null);
		}

		public void reqGiveGold(UInt64 arg1, string arg2)
		{
			Bundle pBundle = newCall("reqGiveGold", 0);
			if(pBundle == null)
				return;

			bundle.writeUint64(arg1);
			bundle.writeUnicode(arg2);
			sendCall(null);
		}

		public void reqLookMail(Int32 arg1)
		{
			Bundle pBundle = newCall("reqLookMail", 0);
			if(pBundle == null)
				return;

			bundle.writeInt32(arg1);
			sendCall(null);
		}

		public void reqSendMail(UInt64 arg1, string arg2, Byte arg3, string arg4)
		{
			Bundle pBundle = newCall("reqSendMail", 0);
			if(pBundle == null)
				return;

			bundle.writeUint64(arg1);
			bundle.writeUnicode(arg2);
			bundle.writeUint8(arg3);
			bundle.writeUnicode(arg4);
			sendCall(null);
		}

	}

	public class EntityCellEntityCall_AccountBase : EntityCall
	{

		public EntityCellEntityCall_AccountBase(Int32 eid, string ename) : base(eid, ename)
		{
			type = ENTITYCALL_TYPE.ENTITYCALL_TYPE_CELL;
		}

		public void LeaveRoom()
		{
			Bundle pBundle = newCall("LeaveRoom", 0);
			if(pBundle == null)
				return;

			sendCall(null);
		}

	}
	}
