/*
	Generated by KBEngine!
	Please do not modify this file!
	tools = kbcmd
*/

namespace KBEngine
{
	using UnityEngine;
	using System;
	using System.Collections;
	using System.Collections.Generic;

	public class EntityDef
	{
		public static Dictionary<string, UInt16> datatype2id = new Dictionary<string, UInt16>();
		public static Dictionary<string, DATATYPE_BASE> datatypes = new Dictionary<string, DATATYPE_BASE>();
		public static Dictionary<UInt16, DATATYPE_BASE> id2datatypes = new Dictionary<UInt16, DATATYPE_BASE>();
		public static Dictionary<string, Int32> entityclass = new Dictionary<string, Int32>();
		public static Dictionary<string, ScriptModule> moduledefs = new Dictionary<string, ScriptModule>();
		public static Dictionary<UInt16, ScriptModule> idmoduledefs = new Dictionary<UInt16, ScriptModule>();

		public static bool init()
		{
			initDataTypes();
			initDefTypes();
			initScriptModules();
			return true;
		}

		public static bool reset()
		{
			clear();
			return init();
		}

		public static void clear()
		{
			datatype2id.Clear();
			datatypes.Clear();
			id2datatypes.Clear();
			entityclass.Clear();
			moduledefs.Clear();
			idmoduledefs.Clear();
		}

		public static void initDataTypes()
		{
			datatypes["UINT8"] = new DATATYPE_UINT8();
			datatypes["UINT16"] = new DATATYPE_UINT16();
			datatypes["UINT32"] = new DATATYPE_UINT32();
			datatypes["UINT64"] = new DATATYPE_UINT64();

			datatypes["INT8"] = new DATATYPE_INT8();
			datatypes["INT16"] = new DATATYPE_INT16();
			datatypes["INT32"] = new DATATYPE_INT32();
			datatypes["INT64"] = new DATATYPE_INT64();

			datatypes["FLOAT"] = new DATATYPE_FLOAT();
			datatypes["DOUBLE"] = new DATATYPE_DOUBLE();

			datatypes["STRING"] = new DATATYPE_STRING();
			datatypes["VECTOR2"] = new DATATYPE_VECTOR2();

			datatypes["VECTOR3"] = new DATATYPE_VECTOR3();

			datatypes["VECTOR4"] = new DATATYPE_VECTOR4();
			datatypes["PYTHON"] = new DATATYPE_PYTHON();

			datatypes["UNICODE"] = new DATATYPE_UNICODE();
			datatypes["ENTITYCALL"] = new DATATYPE_ENTITYCALL();

			datatypes["BLOB"] = new DATATYPE_BLOB();
		}

		public static void initScriptModules()
		{
			ScriptModule pAccountModule = new ScriptModule("Account");
			EntityDef.moduledefs["Account"] = pAccountModule;
			EntityDef.idmoduledefs[1] = pAccountModule;

			Property pAccount_position = new Property();
			pAccount_position.name = "position";
			pAccount_position.properUtype = 40000;
			pAccount_position.properFlags = 4;
			pAccount_position.aliasID = 1;
			Vector3 Account_position_defval = new Vector3();
			pAccount_position.defaultVal = Account_position_defval;
			pAccountModule.propertys["position"] = pAccount_position; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_position.aliasID] = pAccount_position;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(position / 40000).");

			Property pAccount_direction = new Property();
			pAccount_direction.name = "direction";
			pAccount_direction.properUtype = 40001;
			pAccount_direction.properFlags = 4;
			pAccount_direction.aliasID = 2;
			Vector3 Account_direction_defval = new Vector3();
			pAccount_direction.defaultVal = Account_direction_defval;
			pAccountModule.propertys["direction"] = pAccount_direction; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_direction.aliasID] = pAccount_direction;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(direction / 40001).");

			Property pAccount_spaceID = new Property();
			pAccount_spaceID.name = "spaceID";
			pAccount_spaceID.properUtype = 40002;
			pAccount_spaceID.properFlags = 16;
			pAccount_spaceID.aliasID = 3;
			UInt32 Account_spaceID_defval;
			UInt32.TryParse("", out Account_spaceID_defval);
			pAccount_spaceID.defaultVal = Account_spaceID_defval;
			pAccountModule.propertys["spaceID"] = pAccount_spaceID; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_spaceID.aliasID] = pAccount_spaceID;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(spaceID / 40002).");

			Property pAccount_actionData = new Property();
			pAccount_actionData.name = "actionData";
			pAccount_actionData.properUtype = 9;
			pAccount_actionData.properFlags = 16;
			pAccount_actionData.aliasID = 4;
			pAccount_actionData.defaultVal = EntityDef.id2datatypes[27].parseDefaultValStr("");
			pAccountModule.propertys["actionData"] = pAccount_actionData; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_actionData.aliasID] = pAccount_actionData;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(actionData / 9).");

			Property pAccount_holds = new Property();
			pAccount_holds.name = "holds";
			pAccount_holds.properUtype = 8;
			pAccount_holds.properFlags = 16;
			pAccount_holds.aliasID = 5;
			pAccount_holds.defaultVal = EntityDef.id2datatypes[22].parseDefaultValStr("");
			pAccountModule.propertys["holds"] = pAccount_holds; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_holds.aliasID] = pAccount_holds;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(holds / 8).");

			Property pAccount_isNewPlayer = new Property();
			pAccount_isNewPlayer.name = "isNewPlayer";
			pAccount_isNewPlayer.properUtype = 5;
			pAccount_isNewPlayer.properFlags = 32;
			pAccount_isNewPlayer.aliasID = 6;
			Byte Account_isNewPlayer_defval;
			Byte.TryParse("1", out Account_isNewPlayer_defval);
			pAccount_isNewPlayer.defaultVal = Account_isNewPlayer_defval;
			pAccountModule.propertys["isNewPlayer"] = pAccount_isNewPlayer; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_isNewPlayer.aliasID] = pAccount_isNewPlayer;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(isNewPlayer / 5).");

			Property pAccount_isReady = new Property();
			pAccount_isReady.name = "isReady";
			pAccount_isReady.properUtype = 7;
			pAccount_isReady.properFlags = 4;
			pAccount_isReady.aliasID = 7;
			Byte Account_isReady_defval;
			Byte.TryParse("", out Account_isReady_defval);
			pAccount_isReady.defaultVal = Account_isReady_defval;
			pAccountModule.propertys["isReady"] = pAccount_isReady; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_isReady.aliasID] = pAccount_isReady;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(isReady / 7).");

			Property pAccount_playerID = new Property();
			pAccount_playerID.name = "playerID";
			pAccount_playerID.properUtype = 4;
			pAccount_playerID.properFlags = 4;
			pAccount_playerID.aliasID = 8;
			UInt16 Account_playerID_defval;
			UInt16.TryParse("", out Account_playerID_defval);
			pAccount_playerID.defaultVal = Account_playerID_defval;
			pAccountModule.propertys["playerID"] = pAccount_playerID; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_playerID.aliasID] = pAccount_playerID;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(playerID / 4).");

			Property pAccount_playerID_base = new Property();
			pAccount_playerID_base.name = "playerID_base";
			pAccount_playerID_base.properUtype = 2;
			pAccount_playerID_base.properFlags = 32;
			pAccount_playerID_base.aliasID = 9;
			UInt16 Account_playerID_base_defval;
			UInt16.TryParse("", out Account_playerID_base_defval);
			pAccount_playerID_base.defaultVal = Account_playerID_base_defval;
			pAccountModule.propertys["playerID_base"] = pAccount_playerID_base; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_playerID_base.aliasID] = pAccount_playerID_base;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(playerID_base / 2).");

			Property pAccount_playerName = new Property();
			pAccount_playerName.name = "playerName";
			pAccount_playerName.properUtype = 3;
			pAccount_playerName.properFlags = 4;
			pAccount_playerName.aliasID = 10;
			string Account_playerName_defval = "";
			pAccount_playerName.defaultVal = Account_playerName_defval;
			pAccountModule.propertys["playerName"] = pAccount_playerName; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_playerName.aliasID] = pAccount_playerName;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(playerName / 3).");

			Property pAccount_playerName_base = new Property();
			pAccount_playerName_base.name = "playerName_base";
			pAccount_playerName_base.properUtype = 1;
			pAccount_playerName_base.properFlags = 32;
			pAccount_playerName_base.aliasID = 11;
			string Account_playerName_base_defval = "";
			pAccount_playerName_base.defaultVal = Account_playerName_base_defval;
			pAccountModule.propertys["playerName_base"] = pAccount_playerName_base; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_playerName_base.aliasID] = pAccount_playerName_base;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(playerName_base / 1).");

			Property pAccount_roomSeatIndex = new Property();
			pAccount_roomSeatIndex.name = "roomSeatIndex";
			pAccount_roomSeatIndex.properUtype = 6;
			pAccount_roomSeatIndex.properFlags = 4;
			pAccount_roomSeatIndex.aliasID = 12;
			Byte Account_roomSeatIndex_defval;
			Byte.TryParse("", out Account_roomSeatIndex_defval);
			pAccount_roomSeatIndex.defaultVal = Account_roomSeatIndex_defval;
			pAccountModule.propertys["roomSeatIndex"] = pAccount_roomSeatIndex; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_roomSeatIndex.aliasID] = pAccount_roomSeatIndex;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(roomSeatIndex / 6).");

			List<DATATYPE_BASE> pAccount_OnReqCreateAvatar_args = new List<DATATYPE_BASE>();
			pAccount_OnReqCreateAvatar_args.Add(EntityDef.id2datatypes[2]);

			Method pAccount_OnReqCreateAvatar = new Method();
			pAccount_OnReqCreateAvatar.name = "OnReqCreateAvatar";
			pAccount_OnReqCreateAvatar.methodUtype = 19;
			pAccount_OnReqCreateAvatar.aliasID = 1;
			pAccount_OnReqCreateAvatar.args = pAccount_OnReqCreateAvatar_args;

			pAccountModule.methods["OnReqCreateAvatar"] = pAccount_OnReqCreateAvatar; 
			pAccountModule.useMethodDescrAlias = true;
			pAccountModule.idmethods[(UInt16)pAccount_OnReqCreateAvatar.aliasID] = pAccount_OnReqCreateAvatar;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(OnReqCreateAvatar / 19).");

			List<DATATYPE_BASE> pAccount_game_begin_push_args = new List<DATATYPE_BASE>();

			Method pAccount_game_begin_push = new Method();
			pAccount_game_begin_push.name = "game_begin_push";
			pAccount_game_begin_push.methodUtype = 22;
			pAccount_game_begin_push.aliasID = 2;
			pAccount_game_begin_push.args = pAccount_game_begin_push_args;

			pAccountModule.methods["game_begin_push"] = pAccount_game_begin_push; 
			pAccountModule.useMethodDescrAlias = true;
			pAccountModule.idmethods[(UInt16)pAccount_game_begin_push.aliasID] = pAccount_game_begin_push;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(game_begin_push / 22).");

			List<DATATYPE_BASE> pAccount_game_chupai_push_args = new List<DATATYPE_BASE>();

			Method pAccount_game_chupai_push = new Method();
			pAccount_game_chupai_push.name = "game_chupai_push";
			pAccount_game_chupai_push.methodUtype = 25;
			pAccount_game_chupai_push.aliasID = 3;
			pAccount_game_chupai_push.args = pAccount_game_chupai_push_args;

			pAccountModule.methods["game_chupai_push"] = pAccount_game_chupai_push; 
			pAccountModule.useMethodDescrAlias = true;
			pAccountModule.idmethods[(UInt16)pAccount_game_chupai_push.aliasID] = pAccount_game_chupai_push;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(game_chupai_push / 25).");

			List<DATATYPE_BASE> pAccount_game_mopai_push_args = new List<DATATYPE_BASE>();
			pAccount_game_mopai_push_args.Add(EntityDef.id2datatypes[6]);

			Method pAccount_game_mopai_push = new Method();
			pAccount_game_mopai_push.name = "game_mopai_push";
			pAccount_game_mopai_push.methodUtype = 27;
			pAccount_game_mopai_push.aliasID = 4;
			pAccount_game_mopai_push.args = pAccount_game_mopai_push_args;

			pAccountModule.methods["game_mopai_push"] = pAccount_game_mopai_push; 
			pAccountModule.useMethodDescrAlias = true;
			pAccountModule.idmethods[(UInt16)pAccount_game_mopai_push.aliasID] = pAccount_game_mopai_push;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(game_mopai_push / 27).");

			List<DATATYPE_BASE> pAccount_has_action_args = new List<DATATYPE_BASE>();

			Method pAccount_has_action = new Method();
			pAccount_has_action.name = "has_action";
			pAccount_has_action.methodUtype = 24;
			pAccount_has_action.aliasID = 5;
			pAccount_has_action.args = pAccount_has_action_args;

			pAccountModule.methods["has_action"] = pAccount_has_action; 
			pAccountModule.useMethodDescrAlias = true;
			pAccountModule.idmethods[(UInt16)pAccount_has_action.aliasID] = pAccount_has_action;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(has_action / 24).");

			List<DATATYPE_BASE> pAccount_onGang_args = new List<DATATYPE_BASE>();
			pAccount_onGang_args.Add(EntityDef.id2datatypes[4]);
			pAccount_onGang_args.Add(EntityDef.id2datatypes[6]);
			pAccount_onGang_args.Add(EntityDef.id2datatypes[12]);

			Method pAccount_onGang = new Method();
			pAccount_onGang.name = "onGang";
			pAccount_onGang.methodUtype = 30;
			pAccount_onGang.aliasID = 6;
			pAccount_onGang.args = pAccount_onGang_args;

			pAccountModule.methods["onGang"] = pAccount_onGang; 
			pAccountModule.useMethodDescrAlias = true;
			pAccountModule.idmethods[(UInt16)pAccount_onGang.aliasID] = pAccount_onGang;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(onGang / 30).");

			List<DATATYPE_BASE> pAccount_onGetRoomInfo_args = new List<DATATYPE_BASE>();
			pAccount_onGetRoomInfo_args.Add(EntityDef.id2datatypes[26]);

			Method pAccount_onGetRoomInfo = new Method();
			pAccount_onGetRoomInfo.name = "onGetRoomInfo";
			pAccount_onGetRoomInfo.methodUtype = 21;
			pAccount_onGetRoomInfo.aliasID = 7;
			pAccount_onGetRoomInfo.args = pAccount_onGetRoomInfo_args;

			pAccountModule.methods["onGetRoomInfo"] = pAccount_onGetRoomInfo; 
			pAccountModule.useMethodDescrAlias = true;
			pAccountModule.idmethods[(UInt16)pAccount_onGetRoomInfo.aliasID] = pAccount_onGetRoomInfo;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(onGetRoomInfo / 21).");

			List<DATATYPE_BASE> pAccount_onHu_args = new List<DATATYPE_BASE>();
			pAccount_onHu_args.Add(EntityDef.id2datatypes[4]);
			pAccount_onHu_args.Add(EntityDef.id2datatypes[2]);
			pAccount_onHu_args.Add(EntityDef.id2datatypes[6]);

			Method pAccount_onHu = new Method();
			pAccount_onHu.name = "onHu";
			pAccount_onHu.methodUtype = 31;
			pAccount_onHu.aliasID = 8;
			pAccount_onHu.args = pAccount_onHu_args;

			pAccountModule.methods["onHu"] = pAccount_onHu; 
			pAccountModule.useMethodDescrAlias = true;
			pAccountModule.idmethods[(UInt16)pAccount_onHu.aliasID] = pAccount_onHu;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(onHu / 31).");

			List<DATATYPE_BASE> pAccount_onPlayCard_args = new List<DATATYPE_BASE>();
			pAccount_onPlayCard_args.Add(EntityDef.id2datatypes[4]);
			pAccount_onPlayCard_args.Add(EntityDef.id2datatypes[6]);

			Method pAccount_onPlayCard = new Method();
			pAccount_onPlayCard.name = "onPlayCard";
			pAccount_onPlayCard.methodUtype = 26;
			pAccount_onPlayCard.aliasID = 9;
			pAccount_onPlayCard.args = pAccount_onPlayCard_args;

			pAccountModule.methods["onPlayCard"] = pAccount_onPlayCard; 
			pAccountModule.useMethodDescrAlias = true;
			pAccountModule.idmethods[(UInt16)pAccount_onPlayCard.aliasID] = pAccount_onPlayCard;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(onPlayCard / 26).");

			List<DATATYPE_BASE> pAccount_onPlayCardOver_args = new List<DATATYPE_BASE>();
			pAccount_onPlayCardOver_args.Add(EntityDef.id2datatypes[4]);
			pAccount_onPlayCardOver_args.Add(EntityDef.id2datatypes[6]);

			Method pAccount_onPlayCardOver = new Method();
			pAccount_onPlayCardOver.name = "onPlayCardOver";
			pAccount_onPlayCardOver.methodUtype = 32;
			pAccount_onPlayCardOver.aliasID = 10;
			pAccount_onPlayCardOver.args = pAccount_onPlayCardOver_args;

			pAccountModule.methods["onPlayCardOver"] = pAccount_onPlayCardOver; 
			pAccountModule.useMethodDescrAlias = true;
			pAccountModule.idmethods[(UInt16)pAccount_onPlayCardOver.aliasID] = pAccount_onPlayCardOver;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(onPlayCardOver / 32).");

			List<DATATYPE_BASE> pAccount_otherPlayerMopai_args = new List<DATATYPE_BASE>();
			pAccount_otherPlayerMopai_args.Add(EntityDef.id2datatypes[4]);

			Method pAccount_otherPlayerMopai = new Method();
			pAccount_otherPlayerMopai.name = "otherPlayerMopai";
			pAccount_otherPlayerMopai.methodUtype = 28;
			pAccount_otherPlayerMopai.aliasID = 11;
			pAccount_otherPlayerMopai.args = pAccount_otherPlayerMopai_args;

			pAccountModule.methods["otherPlayerMopai"] = pAccount_otherPlayerMopai; 
			pAccountModule.useMethodDescrAlias = true;
			pAccountModule.idmethods[(UInt16)pAccount_otherPlayerMopai.aliasID] = pAccount_otherPlayerMopai;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(otherPlayerMopai / 28).");

			List<DATATYPE_BASE> pAccount_peng_notify_push_args = new List<DATATYPE_BASE>();
			pAccount_peng_notify_push_args.Add(EntityDef.id2datatypes[4]);
			pAccount_peng_notify_push_args.Add(EntityDef.id2datatypes[6]);

			Method pAccount_peng_notify_push = new Method();
			pAccount_peng_notify_push.name = "peng_notify_push";
			pAccount_peng_notify_push.methodUtype = 29;
			pAccount_peng_notify_push.aliasID = 12;
			pAccount_peng_notify_push.args = pAccount_peng_notify_push_args;

			pAccountModule.methods["peng_notify_push"] = pAccount_peng_notify_push; 
			pAccountModule.useMethodDescrAlias = true;
			pAccountModule.idmethods[(UInt16)pAccount_peng_notify_push.aliasID] = pAccount_peng_notify_push;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(peng_notify_push / 29).");

			List<DATATYPE_BASE> pAccount_playerLevelRoom_args = new List<DATATYPE_BASE>();

			Method pAccount_playerLevelRoom = new Method();
			pAccount_playerLevelRoom.name = "playerLevelRoom";
			pAccount_playerLevelRoom.methodUtype = 20;
			pAccount_playerLevelRoom.aliasID = 13;
			pAccount_playerLevelRoom.args = pAccount_playerLevelRoom_args;

			pAccountModule.methods["playerLevelRoom"] = pAccount_playerLevelRoom; 
			pAccountModule.useMethodDescrAlias = true;
			pAccountModule.idmethods[(UInt16)pAccount_playerLevelRoom.aliasID] = pAccount_playerLevelRoom;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(playerLevelRoom / 20).");

			List<DATATYPE_BASE> pAccount_upDataClientRoomInfo_args = new List<DATATYPE_BASE>();
			pAccount_upDataClientRoomInfo_args.Add(EntityDef.id2datatypes[26]);

			Method pAccount_upDataClientRoomInfo = new Method();
			pAccount_upDataClientRoomInfo.name = "upDataClientRoomInfo";
			pAccount_upDataClientRoomInfo.methodUtype = 23;
			pAccount_upDataClientRoomInfo.aliasID = 14;
			pAccount_upDataClientRoomInfo.args = pAccount_upDataClientRoomInfo_args;

			pAccountModule.methods["upDataClientRoomInfo"] = pAccount_upDataClientRoomInfo; 
			pAccountModule.useMethodDescrAlias = true;
			pAccountModule.idmethods[(UInt16)pAccount_upDataClientRoomInfo.aliasID] = pAccount_upDataClientRoomInfo;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(upDataClientRoomInfo / 23).");

			List<DATATYPE_BASE> pAccount_EnterMatchesMatch_args = new List<DATATYPE_BASE>();

			Method pAccount_EnterMatchesMatch = new Method();
			pAccount_EnterMatchesMatch.name = "EnterMatchesMatch";
			pAccount_EnterMatchesMatch.methodUtype = 13;
			pAccount_EnterMatchesMatch.aliasID = -1;
			pAccount_EnterMatchesMatch.args = pAccount_EnterMatchesMatch_args;

			pAccountModule.methods["EnterMatchesMatch"] = pAccount_EnterMatchesMatch; 
			pAccountModule.base_methods["EnterMatchesMatch"] = pAccount_EnterMatchesMatch;

			pAccountModule.idbase_methods[pAccount_EnterMatchesMatch.methodUtype] = pAccount_EnterMatchesMatch;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(EnterMatchesMatch / 13).");

			List<DATATYPE_BASE> pAccount_reqChangeRoom_args = new List<DATATYPE_BASE>();

			Method pAccount_reqChangeRoom = new Method();
			pAccount_reqChangeRoom.name = "reqChangeRoom";
			pAccount_reqChangeRoom.methodUtype = 15;
			pAccount_reqChangeRoom.aliasID = -1;
			pAccount_reqChangeRoom.args = pAccount_reqChangeRoom_args;

			pAccountModule.methods["reqChangeRoom"] = pAccount_reqChangeRoom; 
			pAccountModule.base_methods["reqChangeRoom"] = pAccount_reqChangeRoom;

			pAccountModule.idbase_methods[pAccount_reqChangeRoom.methodUtype] = pAccount_reqChangeRoom;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(reqChangeRoom / 15).");

			List<DATATYPE_BASE> pAccount_reqCreateAvatar_args = new List<DATATYPE_BASE>();
			pAccount_reqCreateAvatar_args.Add(EntityDef.id2datatypes[12]);

			Method pAccount_reqCreateAvatar = new Method();
			pAccount_reqCreateAvatar.name = "reqCreateAvatar";
			pAccount_reqCreateAvatar.methodUtype = 11;
			pAccount_reqCreateAvatar.aliasID = -1;
			pAccount_reqCreateAvatar.args = pAccount_reqCreateAvatar_args;

			pAccountModule.methods["reqCreateAvatar"] = pAccount_reqCreateAvatar; 
			pAccountModule.base_methods["reqCreateAvatar"] = pAccount_reqCreateAvatar;

			pAccountModule.idbase_methods[pAccount_reqCreateAvatar.methodUtype] = pAccount_reqCreateAvatar;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(reqCreateAvatar / 11).");

			List<DATATYPE_BASE> pAccount_LeaveRoom_args = new List<DATATYPE_BASE>();

			Method pAccount_LeaveRoom = new Method();
			pAccount_LeaveRoom.name = "LeaveRoom";
			pAccount_LeaveRoom.methodUtype = 1;
			pAccount_LeaveRoom.aliasID = -1;
			pAccount_LeaveRoom.args = pAccount_LeaveRoom_args;

			pAccountModule.methods["LeaveRoom"] = pAccount_LeaveRoom; 
			pAccountModule.cell_methods["LeaveRoom"] = pAccount_LeaveRoom;

			pAccountModule.idcell_methods[pAccount_LeaveRoom.methodUtype] = pAccount_LeaveRoom;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(LeaveRoom / 1).");

			ScriptModule pRoomModule = new ScriptModule("Room");
			EntityDef.moduledefs["Room"] = pRoomModule;
			EntityDef.idmoduledefs[4] = pRoomModule;

			Property pRoom_position = new Property();
			pRoom_position.name = "position";
			pRoom_position.properUtype = 40000;
			pRoom_position.properFlags = 4;
			pRoom_position.aliasID = 1;
			Vector3 Room_position_defval = new Vector3();
			pRoom_position.defaultVal = Room_position_defval;
			pRoomModule.propertys["position"] = pRoom_position; 

			pRoomModule.usePropertyDescrAlias = true;
			pRoomModule.idpropertys[(UInt16)pRoom_position.aliasID] = pRoom_position;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Room), property(position / 40000).");

			Property pRoom_direction = new Property();
			pRoom_direction.name = "direction";
			pRoom_direction.properUtype = 40001;
			pRoom_direction.properFlags = 4;
			pRoom_direction.aliasID = 2;
			Vector3 Room_direction_defval = new Vector3();
			pRoom_direction.defaultVal = Room_direction_defval;
			pRoomModule.propertys["direction"] = pRoom_direction; 

			pRoomModule.usePropertyDescrAlias = true;
			pRoomModule.idpropertys[(UInt16)pRoom_direction.aliasID] = pRoom_direction;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Room), property(direction / 40001).");

			Property pRoom_spaceID = new Property();
			pRoom_spaceID.name = "spaceID";
			pRoom_spaceID.properUtype = 40002;
			pRoom_spaceID.properFlags = 16;
			pRoom_spaceID.aliasID = 3;
			UInt32 Room_spaceID_defval;
			UInt32.TryParse("", out Room_spaceID_defval);
			pRoom_spaceID.defaultVal = Room_spaceID_defval;
			pRoomModule.propertys["spaceID"] = pRoom_spaceID; 

			pRoomModule.usePropertyDescrAlias = true;
			pRoomModule.idpropertys[(UInt16)pRoom_spaceID.aliasID] = pRoom_spaceID;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Room), property(spaceID / 40002).");

			Property pRoom_RoomType = new Property();
			pRoom_RoomType.name = "RoomType";
			pRoom_RoomType.properUtype = 12;
			pRoom_RoomType.properFlags = 4;
			pRoom_RoomType.aliasID = 4;
			Byte Room_RoomType_defval;
			Byte.TryParse("", out Room_RoomType_defval);
			pRoom_RoomType.defaultVal = Room_RoomType_defval;
			pRoomModule.propertys["RoomType"] = pRoom_RoomType; 

			pRoomModule.usePropertyDescrAlias = true;
			pRoomModule.idpropertys[(UInt16)pRoom_RoomType.aliasID] = pRoom_RoomType;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Room), property(RoomType / 12).");

			Property pRoom_cur_turn = new Property();
			pRoom_cur_turn.name = "cur_turn";
			pRoom_cur_turn.properUtype = 17;
			pRoom_cur_turn.properFlags = 4;
			pRoom_cur_turn.aliasID = 5;
			Byte Room_cur_turn_defval;
			Byte.TryParse("", out Room_cur_turn_defval);
			pRoom_cur_turn.defaultVal = Room_cur_turn_defval;
			pRoomModule.propertys["cur_turn"] = pRoom_cur_turn; 

			pRoomModule.usePropertyDescrAlias = true;
			pRoomModule.idpropertys[(UInt16)pRoom_cur_turn.aliasID] = pRoom_cur_turn;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Room), property(cur_turn / 17).");

			Property pRoom_numOfMJ = new Property();
			pRoom_numOfMJ.name = "numOfMJ";
			pRoom_numOfMJ.properUtype = 15;
			pRoom_numOfMJ.properFlags = 4;
			pRoom_numOfMJ.aliasID = 6;
			Byte Room_numOfMJ_defval;
			Byte.TryParse("", out Room_numOfMJ_defval);
			pRoom_numOfMJ.defaultVal = Room_numOfMJ_defval;
			pRoomModule.propertys["numOfMJ"] = pRoom_numOfMJ; 

			pRoomModule.usePropertyDescrAlias = true;
			pRoomModule.idpropertys[(UInt16)pRoom_numOfMJ.aliasID] = pRoom_numOfMJ;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Room), property(numOfMJ / 15).");

			Property pRoom_playerMaxCount = new Property();
			pRoom_playerMaxCount.name = "playerMaxCount";
			pRoom_playerMaxCount.properUtype = 14;
			pRoom_playerMaxCount.properFlags = 4;
			pRoom_playerMaxCount.aliasID = 7;
			Byte Room_playerMaxCount_defval;
			Byte.TryParse("", out Room_playerMaxCount_defval);
			pRoom_playerMaxCount.defaultVal = Room_playerMaxCount_defval;
			pRoomModule.propertys["playerMaxCount"] = pRoom_playerMaxCount; 

			pRoomModule.usePropertyDescrAlias = true;
			pRoomModule.idpropertys[(UInt16)pRoom_playerMaxCount.aliasID] = pRoom_playerMaxCount;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Room), property(playerMaxCount / 14).");

			Property pRoom_public_roomInfo = new Property();
			pRoom_public_roomInfo.name = "public_roomInfo";
			pRoom_public_roomInfo.properUtype = 16;
			pRoom_public_roomInfo.properFlags = 4;
			pRoom_public_roomInfo.aliasID = 8;
			pRoom_public_roomInfo.defaultVal = EntityDef.id2datatypes[26].parseDefaultValStr("");
			pRoomModule.propertys["public_roomInfo"] = pRoom_public_roomInfo; 

			pRoomModule.usePropertyDescrAlias = true;
			pRoomModule.idpropertys[(UInt16)pRoom_public_roomInfo.aliasID] = pRoom_public_roomInfo;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Room), property(public_roomInfo / 16).");

			Property pRoom_roomKey = new Property();
			pRoom_roomKey.name = "roomKey";
			pRoom_roomKey.properUtype = 11;
			pRoom_roomKey.properFlags = 4;
			pRoom_roomKey.aliasID = 9;
			UInt64 Room_roomKey_defval;
			UInt64.TryParse("", out Room_roomKey_defval);
			pRoom_roomKey.defaultVal = Room_roomKey_defval;
			pRoomModule.propertys["roomKey"] = pRoom_roomKey; 

			pRoomModule.usePropertyDescrAlias = true;
			pRoomModule.idpropertys[(UInt16)pRoom_roomKey.aliasID] = pRoom_roomKey;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Room), property(roomKey / 11).");

			List<DATATYPE_BASE> pRoom_chuPai_args = new List<DATATYPE_BASE>();
			pRoom_chuPai_args.Add(EntityDef.id2datatypes[6]);

			Method pRoom_chuPai = new Method();
			pRoom_chuPai.name = "chuPai";
			pRoom_chuPai.methodUtype = 43;
			pRoom_chuPai.aliasID = -1;
			pRoom_chuPai.args = pRoom_chuPai_args;

			pRoomModule.methods["chuPai"] = pRoom_chuPai; 
			pRoomModule.cell_methods["chuPai"] = pRoom_chuPai;

			pRoomModule.idcell_methods[pRoom_chuPai.methodUtype] = pRoom_chuPai;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Room), method(chuPai / 43).");

			List<DATATYPE_BASE> pRoom_reqChangeReadyState_args = new List<DATATYPE_BASE>();
			pRoom_reqChangeReadyState_args.Add(EntityDef.id2datatypes[2]);

			Method pRoom_reqChangeReadyState = new Method();
			pRoom_reqChangeReadyState.name = "reqChangeReadyState";
			pRoom_reqChangeReadyState.methodUtype = 42;
			pRoom_reqChangeReadyState.aliasID = -1;
			pRoom_reqChangeReadyState.args = pRoom_reqChangeReadyState_args;

			pRoomModule.methods["reqChangeReadyState"] = pRoom_reqChangeReadyState; 
			pRoomModule.cell_methods["reqChangeReadyState"] = pRoom_reqChangeReadyState;

			pRoomModule.idcell_methods[pRoom_reqChangeReadyState.methodUtype] = pRoom_reqChangeReadyState;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Room), method(reqChangeReadyState / 42).");

			List<DATATYPE_BASE> pRoom_reqGang_args = new List<DATATYPE_BASE>();
			pRoom_reqGang_args.Add(EntityDef.id2datatypes[6]);

			Method pRoom_reqGang = new Method();
			pRoom_reqGang.name = "reqGang";
			pRoom_reqGang.methodUtype = 45;
			pRoom_reqGang.aliasID = -1;
			pRoom_reqGang.args = pRoom_reqGang_args;

			pRoomModule.methods["reqGang"] = pRoom_reqGang; 
			pRoomModule.cell_methods["reqGang"] = pRoom_reqGang;

			pRoomModule.idcell_methods[pRoom_reqGang.methodUtype] = pRoom_reqGang;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Room), method(reqGang / 45).");

			List<DATATYPE_BASE> pRoom_reqGetRoomInfo_args = new List<DATATYPE_BASE>();

			Method pRoom_reqGetRoomInfo = new Method();
			pRoom_reqGetRoomInfo.name = "reqGetRoomInfo";
			pRoom_reqGetRoomInfo.methodUtype = 41;
			pRoom_reqGetRoomInfo.aliasID = -1;
			pRoom_reqGetRoomInfo.args = pRoom_reqGetRoomInfo_args;

			pRoomModule.methods["reqGetRoomInfo"] = pRoom_reqGetRoomInfo; 
			pRoomModule.cell_methods["reqGetRoomInfo"] = pRoom_reqGetRoomInfo;

			pRoomModule.idcell_methods[pRoom_reqGetRoomInfo.methodUtype] = pRoom_reqGetRoomInfo;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Room), method(reqGetRoomInfo / 41).");

			List<DATATYPE_BASE> pRoom_reqGuo_args = new List<DATATYPE_BASE>();

			Method pRoom_reqGuo = new Method();
			pRoom_reqGuo.name = "reqGuo";
			pRoom_reqGuo.methodUtype = 47;
			pRoom_reqGuo.aliasID = -1;
			pRoom_reqGuo.args = pRoom_reqGuo_args;

			pRoomModule.methods["reqGuo"] = pRoom_reqGuo; 
			pRoomModule.cell_methods["reqGuo"] = pRoom_reqGuo;

			pRoomModule.idcell_methods[pRoom_reqGuo.methodUtype] = pRoom_reqGuo;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Room), method(reqGuo / 47).");

			List<DATATYPE_BASE> pRoom_reqHu_args = new List<DATATYPE_BASE>();

			Method pRoom_reqHu = new Method();
			pRoom_reqHu.name = "reqHu";
			pRoom_reqHu.methodUtype = 46;
			pRoom_reqHu.aliasID = -1;
			pRoom_reqHu.args = pRoom_reqHu_args;

			pRoomModule.methods["reqHu"] = pRoom_reqHu; 
			pRoomModule.cell_methods["reqHu"] = pRoom_reqHu;

			pRoomModule.idcell_methods[pRoom_reqHu.methodUtype] = pRoom_reqHu;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Room), method(reqHu / 46).");

			List<DATATYPE_BASE> pRoom_reqPeng_args = new List<DATATYPE_BASE>();

			Method pRoom_reqPeng = new Method();
			pRoom_reqPeng.name = "reqPeng";
			pRoom_reqPeng.methodUtype = 44;
			pRoom_reqPeng.aliasID = -1;
			pRoom_reqPeng.args = pRoom_reqPeng_args;

			pRoomModule.methods["reqPeng"] = pRoom_reqPeng; 
			pRoomModule.cell_methods["reqPeng"] = pRoom_reqPeng;

			pRoomModule.idcell_methods[pRoom_reqPeng.methodUtype] = pRoom_reqPeng;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Room), method(reqPeng / 44).");

		}

		public static void initDefTypes()
		{
			{
				UInt16 utype = 2;
				string typeName = "BOOL";
				string name = "UINT8";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 3;
				string typeName = "UINT16";
				string name = "UINT16";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 5;
				string typeName = "SPACE_KEY";
				string name = "UINT64";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 4;
				string typeName = "ENTITY_ID";
				string name = "UINT32";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 6;
				string typeName = "MJPAI";
				string name = "INT8";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 7;
				string typeName = "INT16";
				string name = "INT16";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 8;
				string typeName = "INT32";
				string name = "INT32";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 9;
				string typeName = "INT64";
				string name = "INT64";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 1;
				string typeName = "STRING";
				string name = "STRING";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 12;
				string typeName = "UNICODE";
				string name = "UNICODE";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 13;
				string typeName = "FLOAT";
				string name = "FLOAT";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 14;
				string typeName = "DOUBLE";
				string name = "DOUBLE";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 10;
				string typeName = "PYTHON";
				string name = "PYTHON";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 10;
				string typeName = "PY_DICT";
				string name = "PY_DICT";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 10;
				string typeName = "PY_TUPLE";
				string name = "PY_TUPLE";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 10;
				string typeName = "PY_LIST";
				string name = "PY_LIST";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 10;
				string typeName = "ENTITYCALL";
				string name = "ENTITYCALL";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 11;
				string typeName = "BLOB";
				string name = "BLOB";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 15;
				string typeName = "VECTOR2";
				string name = "VECTOR2";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 16;
				string typeName = "VECTOR3";
				string name = "VECTOR3";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 17;
				string typeName = "VECTOR4";
				string name = "VECTOR4";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 22;
				string typeName = "MJ_LIST";
				DATATYPE_MJ_LIST datatype = new DATATYPE_MJ_LIST();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 23;
				string typeName = "ENTITY_LIST";
				DATATYPE_ENTITY_LIST datatype = new DATATYPE_ENTITY_LIST();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 24;
				string typeName = "PLAYER_PUBLIC_INFO";
				DATATYPE_PLAYER_PUBLIC_INFO datatype = new DATATYPE_PLAYER_PUBLIC_INFO();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 25;
				string typeName = "PLAYERINFO_LIST";
				DATATYPE_PLAYERINFO_LIST datatype = new DATATYPE_PLAYERINFO_LIST();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 26;
				string typeName = "ROOM_PUBLIC_INFO";
				DATATYPE_ROOM_PUBLIC_INFO datatype = new DATATYPE_ROOM_PUBLIC_INFO();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 27;
				string typeName = "PLAYER_ACTION_DIC";
				DATATYPE_PLAYER_ACTION_DIC datatype = new DATATYPE_PLAYER_ACTION_DIC();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			foreach(string datatypeStr in EntityDef.datatypes.Keys)
			{
				DATATYPE_BASE dataType = EntityDef.datatypes[datatypeStr];
				if(dataType != null)
				{
					dataType.bind();
				}
			}
		}

	}


}