/*
	Generated by KBEngine!
	Please do not modify this file!
	Please inherit this module, such as: (class Room : RoomBase)
	tools = kbcmd
*/

namespace KBEngine
{
	using UnityEngine;
	using System;
	using System.Collections;
	using System.Collections.Generic;

	// defined in */scripts/entity_defs/Room.def
	// Please inherit and implement "class Room : RoomBase"
	public abstract class RoomBase : Entity
	{
		public EntityBaseEntityCall_RoomBase baseEntityCall = null;
		public EntityCellEntityCall_RoomBase cellEntityCall = null;

		public Byte RoomType = 0;
		public virtual void onRoomTypeChanged(Byte oldValue) {}
		public Byte cur_turn = 0;
		public virtual void onCur_turnChanged(Byte oldValue) {}
		public Byte numOfMJ = 0;
		public virtual void onNumOfMJChanged(Byte oldValue) {}
		public Byte playerMaxCount = 0;
		public virtual void onPlayerMaxCountChanged(Byte oldValue) {}
		public ROOM_PUBLIC_INFO public_roomInfo = new ROOM_PUBLIC_INFO();
		public virtual void onPublic_roomInfoChanged(ROOM_PUBLIC_INFO oldValue) {}
		public UInt64 roomKey = 0;
		public virtual void onRoomKeyChanged(UInt64 oldValue) {}


		public RoomBase()
		{
		}

		public override void onGetBase()
		{
			baseEntityCall = new EntityBaseEntityCall_RoomBase(id, className);
		}

		public override void onGetCell()
		{
			cellEntityCall = new EntityCellEntityCall_RoomBase(id, className);
		}

		public override void onLoseCell()
		{
			cellEntityCall = null;
		}

		public override EntityCall getBaseEntityCall()
		{
			return baseEntityCall;
		}

		public override EntityCall getCellEntityCall()
		{
			return cellEntityCall;
		}

		public override void onRemoteMethodCall(MemoryStream stream)
		{
			ScriptModule sm = EntityDef.moduledefs["Room"];

			UInt16 methodUtype = 0;
			UInt16 componentPropertyUType = 0;

			if(sm.useMethodDescrAlias)
			{
				componentPropertyUType = stream.readUint8();
				methodUtype = stream.readUint8();
			}
			else
			{
				componentPropertyUType = stream.readUint16();
				methodUtype = stream.readUint16();
			}

			Method method = null;

			if(componentPropertyUType == 0)
			{
				method = sm.idmethods[methodUtype];
			}
			else
			{
				Property pComponentPropertyDescription = sm.idpropertys[componentPropertyUType];
				switch(pComponentPropertyDescription.properUtype)
				{
					default:
						break;
				}

				return;
			}

			switch(method.methodUtype)
			{
				default:
					break;
			};
		}

		public override void onUpdatePropertys(MemoryStream stream)
		{
			ScriptModule sm = EntityDef.moduledefs["Room"];
			Dictionary<UInt16, Property> pdatas = sm.idpropertys;

			while(stream.length() > 0)
			{
				UInt16 _t_utype = 0;
				UInt16 _t_child_utype = 0;

				{
					if(sm.usePropertyDescrAlias)
					{
						_t_utype = stream.readUint8();
						_t_child_utype = stream.readUint8();
					}
					else
					{
						_t_utype = stream.readUint16();
						_t_child_utype = stream.readUint16();
					}
				}

				Property prop = null;

				if(_t_utype == 0)
				{
					prop = pdatas[_t_child_utype];
				}
				else
				{
					Property pComponentPropertyDescription = pdatas[_t_utype];
					switch(pComponentPropertyDescription.properUtype)
					{
						default:
							break;
					}

					return;
				}

				switch(prop.properUtype)
				{
					case 11:
						Byte oldval_RoomType = RoomType;
						RoomType = stream.readUint8();

						if(prop.isBase())
						{
							if(inited)
								onRoomTypeChanged(oldval_RoomType);
						}
						else
						{
							if(inWorld)
								onRoomTypeChanged(oldval_RoomType);
						}

						break;
					case 15:
						Byte oldval_cur_turn = cur_turn;
						cur_turn = stream.readUint8();

						if(prop.isBase())
						{
							if(inited)
								onCur_turnChanged(oldval_cur_turn);
						}
						else
						{
							if(inWorld)
								onCur_turnChanged(oldval_cur_turn);
						}

						break;
					case 40001:
						Vector3 oldval_direction = direction;
						direction = stream.readVector3();

						if(prop.isBase())
						{
							if(inited)
								onDirectionChanged(oldval_direction);
						}
						else
						{
							if(inWorld)
								onDirectionChanged(oldval_direction);
						}

						break;
					case 14:
						Byte oldval_numOfMJ = numOfMJ;
						numOfMJ = stream.readUint8();

						if(prop.isBase())
						{
							if(inited)
								onNumOfMJChanged(oldval_numOfMJ);
						}
						else
						{
							if(inWorld)
								onNumOfMJChanged(oldval_numOfMJ);
						}

						break;
					case 13:
						Byte oldval_playerMaxCount = playerMaxCount;
						playerMaxCount = stream.readUint8();

						if(prop.isBase())
						{
							if(inited)
								onPlayerMaxCountChanged(oldval_playerMaxCount);
						}
						else
						{
							if(inWorld)
								onPlayerMaxCountChanged(oldval_playerMaxCount);
						}

						break;
					case 40000:
						Vector3 oldval_position = position;
						position = stream.readVector3();

						if(prop.isBase())
						{
							if(inited)
								onPositionChanged(oldval_position);
						}
						else
						{
							if(inWorld)
								onPositionChanged(oldval_position);
						}

						break;
					case 16:
						ROOM_PUBLIC_INFO oldval_public_roomInfo = public_roomInfo;
						public_roomInfo = ((DATATYPE_ROOM_PUBLIC_INFO)EntityDef.id2datatypes[26]).createFromStreamEx(stream);

						if(prop.isBase())
						{
							if(inited)
								onPublic_roomInfoChanged(oldval_public_roomInfo);
						}
						else
						{
							if(inWorld)
								onPublic_roomInfoChanged(oldval_public_roomInfo);
						}

						break;
					case 10:
						UInt64 oldval_roomKey = roomKey;
						roomKey = stream.readUint64();

						if(prop.isBase())
						{
							if(inited)
								onRoomKeyChanged(oldval_roomKey);
						}
						else
						{
							if(inWorld)
								onRoomKeyChanged(oldval_roomKey);
						}

						break;
					case 40002:
						stream.readUint32();
						break;
					default:
						break;
				};
			}
		}

		public override void callPropertysSetMethods()
		{
			ScriptModule sm = EntityDef.moduledefs["Room"];
			Dictionary<UInt16, Property> pdatas = sm.idpropertys;

			Byte oldval_RoomType = RoomType;
			Property prop_RoomType = pdatas[4];
			if(prop_RoomType.isBase())
			{
				if(inited && !inWorld)
					onRoomTypeChanged(oldval_RoomType);
			}
			else
			{
				if(inWorld)
				{
					if(prop_RoomType.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onRoomTypeChanged(oldval_RoomType);
					}
				}
			}

			Byte oldval_cur_turn = cur_turn;
			Property prop_cur_turn = pdatas[5];
			if(prop_cur_turn.isBase())
			{
				if(inited && !inWorld)
					onCur_turnChanged(oldval_cur_turn);
			}
			else
			{
				if(inWorld)
				{
					if(prop_cur_turn.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onCur_turnChanged(oldval_cur_turn);
					}
				}
			}

			Vector3 oldval_direction = direction;
			Property prop_direction = pdatas[2];
			if(prop_direction.isBase())
			{
				if(inited && !inWorld)
					onDirectionChanged(oldval_direction);
			}
			else
			{
				if(inWorld)
				{
					if(prop_direction.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onDirectionChanged(oldval_direction);
					}
				}
			}

			Byte oldval_numOfMJ = numOfMJ;
			Property prop_numOfMJ = pdatas[6];
			if(prop_numOfMJ.isBase())
			{
				if(inited && !inWorld)
					onNumOfMJChanged(oldval_numOfMJ);
			}
			else
			{
				if(inWorld)
				{
					if(prop_numOfMJ.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onNumOfMJChanged(oldval_numOfMJ);
					}
				}
			}

			Byte oldval_playerMaxCount = playerMaxCount;
			Property prop_playerMaxCount = pdatas[7];
			if(prop_playerMaxCount.isBase())
			{
				if(inited && !inWorld)
					onPlayerMaxCountChanged(oldval_playerMaxCount);
			}
			else
			{
				if(inWorld)
				{
					if(prop_playerMaxCount.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onPlayerMaxCountChanged(oldval_playerMaxCount);
					}
				}
			}

			Vector3 oldval_position = position;
			Property prop_position = pdatas[1];
			if(prop_position.isBase())
			{
				if(inited && !inWorld)
					onPositionChanged(oldval_position);
			}
			else
			{
				if(inWorld)
				{
					if(prop_position.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onPositionChanged(oldval_position);
					}
				}
			}

			ROOM_PUBLIC_INFO oldval_public_roomInfo = public_roomInfo;
			Property prop_public_roomInfo = pdatas[8];
			if(prop_public_roomInfo.isBase())
			{
				if(inited && !inWorld)
					onPublic_roomInfoChanged(oldval_public_roomInfo);
			}
			else
			{
				if(inWorld)
				{
					if(prop_public_roomInfo.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onPublic_roomInfoChanged(oldval_public_roomInfo);
					}
				}
			}

			UInt64 oldval_roomKey = roomKey;
			Property prop_roomKey = pdatas[9];
			if(prop_roomKey.isBase())
			{
				if(inited && !inWorld)
					onRoomKeyChanged(oldval_roomKey);
			}
			else
			{
				if(inWorld)
				{
					if(prop_roomKey.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onRoomKeyChanged(oldval_roomKey);
					}
				}
			}

		}
	}
}